# This is a basic workflow to help you get started with Actions

name: demo-gitops
permissions:
  id-token: write # required to use OIDC authentication
  contents: write # required
  actions: read
  security-events: write
  statuses: write

on:
  push:
    branches: [ main ]
env:
  ECR_REPOSITORY: gitops-argocd

jobs:
  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest


    steps:

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Repository: ${{ github.repository }}
